[build-system]
    requires = ["setuptools>=61.0", "wheel"]
    build-backend = "setuptools.build_meta"

[project]
    name = "jaimead7-parts-sorter-api"
    version = "0.0.1"
    description = "API for a parts sorter system."
    authors = [
        {name = "Jaime Álvarez", email = "alvarez.diaz.jaime1@gmail.com"},
    ]
    maintainers = [
        {name = "Jaime Álvarez", email = "alvarez.diaz.jaime1@gmail.com"},
    ]
    readme = {file = "README.md", content-type = "text/markdown"}
    license = "AGPL-3.0"
    license-files = [
        "LICENSE",
    ]
    keywords = [
        "API",
    ]
    classifiers = [
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ]
    dependencies = [
        "jaimead7-pyutils >= 0.2.0",
        "aiofiles >= 24.1.0",
        "fastapi[standard] >= 0.116.0",
        "sqlmodel >= 0.0.24",
        #TODO: Try not to use ultralytics
        "ncnn >= 1.0.20250916",
        "ultralytics == 8.3.179",
        "torch @ https://download.pytorch.org/whl/cpu/torch-2.5.0%2Bcpu-cp312-cp312-linux_x86_64.whl ; platform_system == 'Linux' and platform_machine != 'aarch64'",
        "torchvision @ https://download.pytorch.org/whl/cpu/torchvision-0.20.0%2Bcpu-cp312-cp312-linux_x86_64.whl ; platform_system == 'Linux' and platform_machine  != 'aarch64'"
    ]
    requires-python = ">=3.10, <3.13"

    [project.optional-dependencies]
        postgres = [
            "asyncpg >= 0.30.0"
        ]
        sqlite = [
            "aiosqlite >= 0.21.0"
        ]
        dev = [
            "pytest"
        ]

    [project.urls]
        Homepage = "https://github.com/Jaimead7/PartsSorter/api"
        Repository = "https://github.com/Jaimead7/PartsSorter"

[tool.setuptools.packages.find]
    where = ['.']
    include = ['*']
    exclude = ['licenses']
